### ISSUE TITLE
NameError: name 'EntropyBinningTransformer' is not defined

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/Auto_ViML#40]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 m, feats, trainm, testm = Auto_ViML(train, target='FloodProbability',test='',
      2                            sample_submission='',
      3                            scoring_parameter='r2', KMeans_Featurizer=False,
      4                            hyper_param='RS',feature_reduction=True,
      5                             Boosting_Flag=True, Binning_Flag=True,
      6                            Add_Poly=3, Stacking_Flag=True,Imbalanced_Flag=False,
      7                            GPU_flag=True, verbose=2)

File /opt/conda/lib/python3.10/site-packages/autoviml/Auto_ViML.py:1404, in Auto_ViML(train, target, test, sample_submission, hyper_param, feature_reduction, scoring_parameter, Boosting_Flag, KMeans_Featurizer, Add_Poly, Stacking_Flag, Binning_Flag, Imbalanced_Flag, GPU_flag, verbose)
   1396 if model_label == 'Single_Label':
   1397     ###############    BINNING   FIRST    TIME ##################################################
   1398     if Binning_Flag and len(saved_num_vars) > 0:
   1399         #### Do binning only when there are numeric features ####
   1400         #### When we Bin the first time, we set the entropy_binning flag to False so
   1401         ####    no numeric variables are removed. But next time, we will remove them later!
   1402         # Optionally, select top n variables based on their predictive power
   1403         # This step is useful if you want to bin only the most informative variables
-> 1404         entropy_binner = EntropyBinningTransformer(replace_vars=False, modeltype=modeltype, top_n_vars=None)
   1406         # Fit the transformer to the training data
   1407         entropy_binner.fit_transform(X_train, y_train)

NameError: name 'EntropyBinningTransformer' is not defined

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 
thanks for testing it out 👍 
I have fixed it now. upgrade to latest version and let me know.
Auto Vimal

**Comment by GDGauravDutta** [comment]
https://www.kaggle.com/code/gauravduttakiit/pss4e5-auto-viml?scriptVersionId=177290781
Still the same issue
